using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CodeSpirit.SourceGenerator;

[Generator]
public class CodeSpiritServiceGenerator : IIncrementalGenerator
{
    private const string ServiceAttributeName = "CodeSpirit.Core.Attributes.ServiceAttribute";
    private const string RepositoryAttributeName = "CodeSpirit.Core.Attributes.RepositoryAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetServiceRegistrationInfo(ctx))
            .Where(static info => info is not null);

        var combined = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(combined, GenerateServiceRegistration);
    }

    private static ServiceRegistrationInfo? GetServiceRegistrationInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var model = ctx.SemanticModel;
        var symbol = model.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol typeSymbol)
            return null;

        if (typeSymbol.IsAbstract)
            return null;

        var serviceLifetime = ServiceLifetimeKind.Scoped;
        var hasService = false;
        string? interfaceName = null;
        var hasRepository = false;

        foreach (var attr in typeSymbol.GetAttributes())
        {
            var attrClass = attr.AttributeClass;
            if (attrClass is null) continue;

            var fullName = attrClass.ToDisplayString();

            if (fullName == ServiceAttributeName)
            {
                hasService = true;
                foreach (var named in attr.NamedArguments)
                {
                    if (named.Key == "Lifetime" && named.Value.Value is int lifetimeVal)
                    {
                        serviceLifetime = (ServiceLifetimeKind)lifetimeVal;
                    }
                    else if (named.Key == "ServiceType" && named.Value.Value is INamedTypeSymbol st)
                    {
                        interfaceName = st.ToDisplayString();
                    }
                }
            }
            else if (fullName == RepositoryAttributeName)
            {
                hasRepository = true;
            }
        }

        if (!hasService && !hasRepository)
            return null;

        if (interfaceName is null)
        {
            var firstInterface = typeSymbol.AllInterfaces
                .FirstOrDefault(i => !i.ToDisplayString().Contains("ICodeSpiritModule"));

            interfaceName = firstInterface?.ToDisplayString() ?? typeSymbol.ToDisplayString();
        }

        return new ServiceRegistrationInfo
        {
            ClassName = typeSymbol.ToDisplayString(),
            InterfaceName = interfaceName,
            Lifetime = serviceLifetime,
            IsRepository = hasRepository
        };
    }

    private static void GenerateServiceRegistration(
        SourceProductionContext context,
        (Compilation Left, System.Collections.Immutable.ImmutableArray<ServiceRegistrationInfo?> Right) source)
    {
        var allInfos = new List<ServiceRegistrationInfo>();
        var seen = new HashSet<string>();

        foreach (var info in source.Right)
        {
            if (info is not null && seen.Add(info.ClassName))
            {
                allInfos.Add(info);
            }
        }

        if (allInfos.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using CodeSpirit.Core.Interfaces;");
        sb.AppendLine();
        sb.AppendLine("namespace CodeSpirit.AutoGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    public sealed class CodeSpiritGeneratedRegistrar : ICodeSpiritGeneratedRegistrar");
        sb.AppendLine("    {");
        sb.AppendLine("        public void RegisterServices(IServiceCollection services, IConfiguration configuration)");
        sb.AppendLine("        {");

        foreach (var reg in allInfos)
        {
            var lifetimeStr = reg.IsRepository ? "Scoped" : reg.Lifetime switch
            {
                ServiceLifetimeKind.Singleton => "Singleton",
                ServiceLifetimeKind.Scoped => "Scoped",
                ServiceLifetimeKind.Transient => "Transient",
                _ => "Scoped"
            };

            sb.AppendLine($"            services.Add{lifetimeStr}<{reg.InterfaceName}, {reg.ClassName}>();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("CodeSpiritServiceRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal sealed class ServiceRegistrationInfo
{
    public string ClassName { get; set; } = string.Empty;
    public string? InterfaceName { get; set; }
    public ServiceLifetimeKind Lifetime { get; set; } = ServiceLifetimeKind.Scoped;
    public bool IsRepository { get; set; }
}

internal enum ServiceLifetimeKind
{
    Singleton = 0,
    Scoped = 1,
    Transient = 2
}
