using CodeSpirit.Core;
using CodeSpirit.Core.Abstractions;
using CodeSpirit.Core.Attributes;
using CodeSpirit.Core.Interfaces;
using CodeSpirit.Infrastructure.Aop;
using CodeSpirit.Infrastructure.Http;
using CodeSpirit.Infrastructure.Monitoring;
using CodeSpirit.Infrastructure.Routing;
using CodeSpirit.Infrastructure.Scheduling;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Reflection;

namespace CodeSpirit.Infrastructure.AutoConfiguration;

public static class CodeSpiritAutoConfiguration
{
    public static WebApplicationBuilder AddCodeSpirit(this WebApplicationBuilder builder)
    {
        var assemblies = DiscoverAssemblies();

        RegisterGeneratedServices(builder.Services, builder.Configuration, assemblies);

        RegisterAutoServices(builder.Services, assemblies);

        LoadModules(builder.Services, builder.Configuration, assemblies);

        RegisterControllers(builder.Services, assemblies);

        builder.Services.AddCodeSpiritAop();

        builder.Services.AddHttp(builder.Configuration);

        builder.Services.AddScheduling(builder.Configuration, Assemblies.CodeSpirit);

        builder.Services.AddCodeSpiritActuator(builder.Configuration);

        builder.Services.Configure<CodeSpiritOptions>(
            builder.Configuration.GetSection("CodeSpirit"));

        return builder;
    }

    public static WebApplication UseCodeSpirit(this WebApplication app)
    {
        LoadAndConfigureModules(app);

        app.UseMiddleware<CodeSpiritMiddleware>();

        app.UseCodeSpiritActuatorEndpoints();

        app.MapControllers();

        app.MapViewModels();

        app.MapGet("/", () => Results.Ok(new { name = "CodeSpirit", status = "Running" }));

        return app;
    }

    private static void RegisterControllers(IServiceCollection services, List<Assembly> assemblies)
    {
        var mvcBuilder = services.AddControllers();

        foreach (var assembly in assemblies)
        {
            mvcBuilder.AddApplicationPart(assembly);
        }
    }

    private static List<Assembly> DiscoverAssemblies()
    {
        PreloadCodeSpiritAssemblies();
        return Assemblies.CodeSpirit.ToList();
    }

    private static void PreloadCodeSpiritAssemblies()
    {
        try
        {
            var entry = Assembly.GetEntryAssembly();
            var entryDir = Path.GetDirectoryName(entry?.Location);
            if (string.IsNullOrEmpty(entryDir) || !Directory.Exists(entryDir)) return;

            foreach (var dll in Directory.EnumerateFiles(entryDir, "CodeSpirit*.dll", SearchOption.TopDirectoryOnly))
            {
                var name = Path.GetFileNameWithoutExtension(dll);
                try { Assembly.Load(name); }
                catch { }
            }
        }
        catch { }
    }

    private static void RegisterGeneratedServices(
        IServiceCollection services, IConfiguration configuration, List<Assembly> assemblies)
    {
        var foundAny = false;

        foreach (var assembly in assemblies)
        {
            var registrarType = assembly.GetType("CodeSpirit.AutoGenerated.CodeSpiritGeneratedRegistrar");
            if (registrarType is not null &&
                Activator.CreateInstance(registrarType) is ICodeSpiritGeneratedRegistrar registrar)
            {
                registrar.RegisterServices(services, configuration);
                foundAny = true;
            }
        }

        if (foundAny)
            return;
    }

    private static void RegisterAutoServices(IServiceCollection services, List<Assembly> assemblies)
    {
        var registrar = new AutoServiceRegistrar();
        foreach (var assembly in assemblies)
        {
            registrar.RegisterServices(services, assembly);
        }
    }

    private static void LoadModules(
        IServiceCollection services, IConfiguration configuration, List<Assembly> assemblies)
    {
        var activeProfile = configuration.GetValue<string>("CodeSpirit:Profile") ?? "default";
        var moduleLoader = new ModuleLoader();

        foreach (var assembly in assemblies)
        {
            var moduleTypes = moduleLoader.ResolveModuleTopology(assembly);

            foreach (var moduleType in moduleTypes)
            {
                if (!IsProfileActive(moduleType, activeProfile))
                    continue;

                if (Activator.CreateInstance(moduleType) is ICodeSpiritModule moduleInstance)
                {
                    var context = new ServiceConfigurationContext(services, configuration);
                    moduleInstance.ConfigureServices(context);
                }
            }
        }
    }

    private static bool IsProfileActive(Type moduleType, string activeProfile)
    {
        var profileAttr = moduleType.GetCustomAttribute<ConfigurationProfileAttribute>();
        if (profileAttr is null)
            return true;

        var profiles = profileAttr.Profile.Split(',', StringSplitOptions.TrimEntries);
        return profiles.Contains(activeProfile, StringComparer.OrdinalIgnoreCase);
    }

    private static void LoadAndConfigureModules(WebApplication app)
    {
        var configuration = app.Services.GetRequiredService<IConfiguration>();
        var activeProfile = configuration.GetValue<string>("CodeSpirit:Profile") ?? "default";
        var moduleLoader = new ModuleLoader();
        var assemblies = DiscoverAssemblies();

        foreach (var assembly in assemblies)
        {
            var moduleTypes = moduleLoader.ResolveModuleTopology(assembly);
            foreach (var moduleType in moduleTypes)
            {
                if (!IsProfileActive(moduleType, activeProfile))
                    continue;

                if (Activator.CreateInstance(moduleType) is ICodeSpiritModule moduleInstance)
                {
                    moduleInstance.Configure(app.Services);
                }
            }
        }
    }
}

public class CodeSpiritOptions
{
    public string Name { get; set; } = "CodeSpirit Application";
    public string Version { get; set; } = "1.0.0";
    public string Profile { get; set; } = "default";
}

public class CodeSpiritMiddleware
{
    private readonly RequestDelegate _next;

    public CodeSpiritMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        context.Response.Headers["X-Powered-By"] = "CodeSpirit";
        await _next(context);
    }
}
