using CodeSpirit.Core;
using CodeSpirit.Core.Abstractions;
using CodeSpirit.Core.Attributes;
using CodeSpirit.Core.Interfaces;
using CodeSpirit.Infrastructure.Aop;
using CodeSpirit.Infrastructure.Http;
using CodeSpirit.Infrastructure.Monitoring;
using CodeSpirit.Infrastructure.Routing;
using CodeSpirit.Infrastructure.Scheduling;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System.Reflection;

namespace CodeSpirit.Infrastructure.AutoConfiguration;

public static class CodeSpiritAutoConfiguration
{
    private static List<Assembly>? _cachedAssemblies;

    public static WebApplicationBuilder AddCodeSpirit(this WebApplicationBuilder builder)
    {
        var assemblies = _cachedAssemblies = DiscoverAssemblies();

        RegisterGeneratedServices(builder.Services, builder.Configuration, assemblies);

        RegisterAutoServices(builder.Services, builder.Configuration, assemblies);

        RunModules(
            builder.Services, builder.Configuration, assemblies,
            (module, services, config) => module.ConfigureServices(new ServiceConfigurationContext(services, config)));

        RegisterControllers(builder.Services, assemblies);

        builder.Services.AddCodeSpiritAop();

        builder.Services.AddHttp(builder.Configuration);

        builder.Services.AddScheduling(builder.Configuration, Assemblies.CodeSpirit);

        builder.Services.AddCodeSpiritActuator(builder.Configuration);

        builder.Services.AddCodeSpiritAttributeInjection();

        builder.Services.Configure<CodeSpiritOptions>(
            builder.Configuration.GetSection("CodeSpirit"));

        return builder;
    }

    public static WebApplication UseCodeSpirit(this WebApplication app)
    {
        var assemblies = _cachedAssemblies ?? DiscoverAssemblies();

        RunModules(
            app.Services, app.Configuration, assemblies,
            (module, _, _) => module.Configure(app.Services));

        app.UseMiddleware<CodeSpiritMiddleware>();

        app.UseStaticFiles();

        app.UseCodeSpiritActuatorEndpoints();

        app.MapControllers();

        app.MapViewModels();

        if (!HasViewModelRoute("/"))
        {
            app.MapGet("/", () => Results.Ok(new { name = "CodeSpirit", status = "Running" }));
        }

        return app;
    }

    private static bool HasViewModelRoute(string route)
    {
        return Assemblies.Find<ViewModel>()
            .Any(vm => string.Equals(ViewModel.GetRoute(vm), route, StringComparison.OrdinalIgnoreCase));
    }

    private static void RegisterControllers(IServiceCollection services, List<Assembly> assemblies)
    {
        var mvcBuilder = services.AddControllers();

        foreach (var assembly in assemblies)
        {
            mvcBuilder.AddApplicationPart(assembly);
        }
    }

    private static List<Assembly> DiscoverAssemblies() => Assemblies.CodeSpirit.ToList();

    private static void RegisterGeneratedServices(
        IServiceCollection services, IConfiguration configuration, List<Assembly> assemblies)
    {
        var foundAny = false;

        foreach (var assembly in assemblies)
        {
            var registrarType = assembly.GetType("CodeSpirit.AutoGenerated.CodeSpiritGeneratedRegistrar");
            if (registrarType is not null &&
                Activator.CreateInstance(registrarType) is ICodeSpiritGeneratedRegistrar registrar)
            {
                registrar.RegisterServices(services, configuration);
                foundAny = true;
            }
        }

        if (foundAny)
            return;
    }

    private static void RegisterAutoServices(IServiceCollection services, IConfiguration configuration, List<Assembly> assemblies)
    {
        var registrar = new AutoServiceRegistrar();
        foreach (var assembly in assemblies)
        {
            registrar.RegisterServices(services, assembly, configuration);
        }
    }

    private static void RunModules(
        IServiceCollection services,
        IConfiguration configuration,
        List<Assembly> assemblies,
        Action<ICodeSpiritModule, IServiceCollection, IConfiguration> configureAction)
    {
        RunModulesCore(assemblies, configuration, module => configureAction(module, services, configuration));
    }

    private static void RunModules(
        IServiceProvider serviceProvider,
        IConfiguration configuration,
        List<Assembly> assemblies,
        Action<ICodeSpiritModule, IServiceProvider, IConfiguration> configureAction)
    {
        RunModulesCore(assemblies, configuration, module => configureAction(module, serviceProvider, configuration));
    }

    private static void RunModulesCore(
        List<Assembly> assemblies,
        IConfiguration configuration,
        Action<ICodeSpiritModule> configure)
    {
        var activeProfile = configuration.GetValue<string>(CodeSpiritDefaults.ProfileKey) ?? CodeSpiritDefaults.ProfileDefault;
        var moduleLoader = new ModuleLoader();

        foreach (var assembly in assemblies)
        {
            var moduleTypes = moduleLoader.ResolveModuleTopology(assembly);

            foreach (var moduleType in moduleTypes)
            {
                if (!IsProfileActive(moduleType, activeProfile))
                    continue;

                if (!IsClassConditionSatisfied(moduleType))
                    continue;

                if (Activator.CreateInstance(moduleType) is ICodeSpiritModule moduleInstance)
                {
                    configure(moduleInstance);
                }
            }
        }
    }

    private static bool IsProfileActive(Type moduleType, string activeProfile)
    {
        var profileAttr = moduleType.GetCustomAttribute<ConfigurationProfileAttribute>();
        if (profileAttr is null)
            return true;

        var profiles = profileAttr.Profile.Split(',', StringSplitOptions.TrimEntries);
        return profiles.Contains(activeProfile, StringComparer.OrdinalIgnoreCase);
    }

    private static bool IsClassConditionSatisfied(Type moduleType)
    {
        var conditional = moduleType.GetCustomAttribute<ConditionalOnClassAttribute>();
        if (conditional is null)
            return true;

        if (conditional.ClassType is { } classType)
            return Assemblies.All.Any(a => a.GetType(classType.FullName!) is not null);

        if (conditional.ClassName is { } className)
            return Assemblies.All.Any(a => a.GetType(className) is not null);

        return true;
    }
}

public class CodeSpiritOptions
{
    public string Name { get; set; } = "CodeSpirit Application";
    public string Version { get; set; } = "1.0.0";
    public string Profile { get; set; } = CodeSpiritDefaults.ProfileDefault;
}

public class CodeSpiritMiddleware
{
    private readonly RequestDelegate _next;

    public CodeSpiritMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        context.Response.Headers[CodeSpiritDefaults.PoweredByHeader] = CodeSpiritDefaults.ProductName;
        await _next(context);
    }
}
